import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography
          variant={"h1"}
          component={motion.h1}
          initial="hidden"
          animate="visible"
          variants={{
            hidden: {
              scale: 0.8,
              opacity: 0,
            },
            visible: {
              scale: 1,
              opacity: 1,
              transition: {
                delay: 0.4,
              },
            },
          }}
          className={styles.title}
        >
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/anasnew99/">My Website!</a>
        </Typography>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          © {new Date().getFullYear()}, Built By Anas Aneeque
          {/*copyright */}
        </a>
      </footer>
    </div>
  );
};

// copyright in html
// <div className={styles.copyright}>
//   <p>
//     © {new Date().getFullYear()}, Built with
//     {` `}

export default Home;
